name: ci
on: [push]
jobs:
  lint:
    name: Lint data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install prettier
        run: npm install -g prettier

      - name: Lint data
        run: prettier --check .

  verify:
    name: Verify data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: scripts

      - name: Verify data
        run: node scripts/verify.js
